pluginManagement {
    includeBuild("build-logic")
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "nowinandroid"
include(":e6:task:app:t2do-app")
include(":e6:task:core:ui")
include(":e6:task:core:designsystem")
include(":e6:task:core:data")
include(":e6:task:core:model")

include(":e6:canasta:app:grocery-app")
include(":e6:canasta:app:grocery-mock")
include(":e6:canasta:core:designsystem")
include(":e6:canasta:core:ui")
include(":e6:canasta:core:domain")
include(":e6:canasta:feature:chat:channels")
// include(":e6:canasta:feature:grocery:search-items")
// include(":e6:canasta:feature:grocery:add-item")
include(":e6:canasta:feature:grocery:create-list")
include(":e6:canasta:feature:grocery:edit-list")
include(":e6:canasta:feature:grocery:grocery-inbox")
include(":e6:core:domain")
include(":e6:core:model")
include(":e6:movies:core:domain")
include(":e6:movies:core:model")
include(":e6:movies:core:data")
include(":e6:movies:core:testing")
include(":e6:movies:core:data-test")
include(":e6:movies:core:database")
include(":e6:movies:core:datastore")
include(":e6:movies:core:datastore-test")
include(":e6:movies:core:network")

include(":app")
include(":nia-app")
include(":app-nia-catalog")
include(":benchmarks")
include(":core:common")
include(":core:data")
include(":core:data-test")
include(":core:database")
include(":core:datastore")
include(":core:datastore-test")
include(":core:designsystem")
include(":core:domain")
include(":core:model")
include(":core:network")
include(":core:ui")
include(":core:testing")
include(":feature:foryou")
include(":feature:interests")
include(":feature:bookmarks")
include(":feature:topic")
include(":feature:settings")
include(":lint")
include(":sync:work")
include(":sync:sync-test")
include(":ui-test-hilt-manifest")
